plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "D:\\Downloads\\opioid_ai_dashboard_full\\frontend\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]